### ISSUE TITLE
Addons without persistence: Ability to add any configurable service (examples: redis)

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#222]
- should be template based
- have plan associated with memory

- Field: name
- Field: category
- Field: Minimum plan
- Field: image
- Field: protocol (TCP/UDP)
- default name, ability to change it, letter, dash, number only
- Documentation, a .md file
- tech logo
- able to map ports
- able to to specify ENV variables

Main parts:
- Populate from github to openode model Addon [DONE]
- Website has website_addons, has a name (defaulted to addon name) [DONE]
- API addons listing [DONE]
- API website_addons listing [DONE]
- API website_addons Create [DONE]
- API website_addons Update [DONE]
- API website_addons Delete [DONE]
- disallow for open source plan [DONE]
- spawn created addons on deployment [DONE]
- Price cost for each if online [DONE]
- stop operation should stop addons (w/ persistence) [DONE]
- adapt logs [DONE]
- adapt exec [DONE]
- memcached addon [DONE]
- add addons repo url in openode.yml, production

**Comment by DatMayo** [comment]
Do you plan to accept `docker-compose.yml` files?

**Comment by martinlevesque** [comment]
Hi,

Unfortunately no, we are stopping to support docker-compose. We will analyze how we should allow to have extra services (ex. redis, databases).

**Comment by DatMayo** [comment]
Okay, but if I would build a Dockerfile with i.E. an mysql in it, would it be banned?

**Comment by martinlevesque** [comment]
No that's not "banned" in Dockerfile, you can do anything possible in Dockerfile.
