### ISSUE TITLE
No env vars

### ISSUE THREAD

**Issue by DatMayo** [openode-io/openode-api#224]
Hey,

I'm using the sitename "dcc-server", which I've deployed ~30 minutes ago. When I have a look @ the docs, it won't recognize my set port.

```typescript
const port: number = Number(process.env.PORT) || 1234;
logger.info(`Listening at http://localhost:${port}/`);
```

Output: 
> <18.03.20 12:39:22> [info]: Listening at http://localhost:1234/

Maybe related to #120 and you can help me :/

**Comment by martinlevesque** [comment]
Will look it shortly

**Comment by martinlevesque** [comment]
Just looked at it. It looks like you do not have a .env file.

Here's a simple example:

```
# ls -la
total 28
drwxrwxr-x  2 root root 4096 Mar 18 08:55 .
drwx------ 17 root root 4096 Mar 18 08:54 ..
-rw-rw-r--  1 root root  396 Mar 16 13:00 Dockerfile
-rw-rw-r--  1 root root   12 Mar 18 08:50 .env
-rw-rw-r--  1 root root   93 Mar 18 08:55 .openode
-rw-rw-r--  1 root root  285 Mar 16 12:58 package.json
-rw-rw-r--  1 root root  320 Mar 18 08:54 server.js
```

package.json:

```
{
  "name": "helloworld",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC"
}
```

.env:

`HELLO=world`

server.js:

```
const http = require("http");

const server = http.createServer(function (req, res) {
	console.log(`server is up! :-)`)
	res.end(`Hello pretty opeNode World ${process.env.HELLO}`);
})

server.listen(80, (err) => {
	if ( ! err) {
		console.log(`node server listening on port 80...`)
	}
})
```

Note that if it's just a PORT, you can always just set it in the Dockerfile:

ENV PORT=80

See the doc here https://www.openode.io/docs/platform/env_vars.md

**Comment by DatMayo** [comment]
My env file is called ".env.prod" which is loaded successfully (i know, its not the right naming convention). But `process.env.PORT` is undefinded. (I don't set it, because I think its set on your side)

My .env.prod looks like this:
```
# Salt Rounds
ROUNDS=12

# Databse
DB_USER=kOn7pmeFNc
DB_PASS=***
DB_DB=secret
DB_HOST=somehost```

**Comment by martinlevesque** [comment]
Hi,

We do not set any environment variables on our side by default.

You can either add PORT=80 in your .env.prod, and make sure to load it before "const port: number = Number(process.env.PORT) || 1234;"

Or you can add a line in Dockerfile:

`ENV PORT=80`

We could however allow to specify a .env filename different than ".env", which I agree can be convenient as in your example. Created a task here https://github.com/openode-io/openode-api/issues/225

**Comment by DatMayo** [comment]
Thx for your help, taht worked :)
