### ISSUE TITLE
Deploy to custom folder

### ISSUE THREAD

**Issue by DatMayo** [openode-io/openode-api#226]
Hey,

is there a way to deploy a different folder? (Like: `openode deploy -f ./dist`)

Background:
I'm using vuejs. By default the page is deployed to /dist. So, when running `npm run build` the /dist folder will be deleted every time the command is executed.

**Comment by martinlevesque** [comment]
Is the problem that you could do "openode deploy" from the dist folder, but when you do the build procedure it erases completely dist and so it would erase the .openode file?

**Comment by DatMayo** [comment]
Correct, the whole folder gets wiped

**Comment by martinlevesque** [comment]
Mmm I am wondering, perhaps you could put your build instruction (npm run build) in your Dockerfile and deploy from ./. In this case our system would take care to build ./dist

**Comment by DatMayo** [comment]
There is a [way to disable](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build) the auto delete with the `--no-clean` param. But I'm not sure how safe/secure it is. (As of bugs)

So I'd rly appreciate if you could add it. (Maybe as a param in the `.opennode` file)

**Comment by DatMayo** [comment]
Btw... I think we should move this discussion to [openode-io/openode-cli](https://github.com/openode-io/openode-cli), because its related to that :)

**Comment by martinlevesque** [comment]
Yeah could be better but we can finish this one here that's fine.

If you could provide a basic project example (minimal) we could look at what best practice should be used.

**Comment by DatMayo** [comment]
You mean an example of a basic vue template?

**Comment by martinlevesque** [comment]
Yes, a "hello world" illustrating your issue would be great.

**Comment by DatMayo** [comment]
Have a look at [here](https://cli.vuejs.org/guide/creating-a-project.html#vue-create)

**Comment by martinlevesque** [comment]
It can be accomplished using instructions in the Dockerfile. We added a documentation guide over here https://www.openode.io/docs/best_practices/build_frontend.md and also sample https://github.com/openode-io/vuejs-hello-world
