### ISSUE TITLE
Check out to enable CORS over the API

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#347]

**Comment by lvenier** [comment]
@martinlevesque : not sure if it is implemented but I get the 'OPTIONS' method not working.
Request URL: https://api.openode.io/instances/summary?with=env,collaborators
Request Method: OPTIONS
Status Code: 404 

Looks to be denying Option method needed for preflight...

**Comment by martinlevesque** [comment]
We don't support the OPTIONS method.

You can check that this header access-control-allow-origin: *
is set in the response header.

**Comment by lvenier** [comment]
@martinlevesque : can you please plan to add the OPTIONS method ? 
it would be usefull for the api to describe supported methods and provide cors description.
It is necessary for preflight.

**Comment by martinlevesque** [comment]
Ah yes, https://github.com/openode-io/openode-api/issues/352
