### ISSUE TITLE
ENV parsed strange

### ISSUE THREAD

**Issue by DatMayo** [openode-io/openode-api#395]
Hey,

I'm running into a weired issue. I set some ENV Vars in my dockerfile. When the script tries to connect, its using the wrong IP. My Provided IP is `188.68.47.103` but the one shown is `104.248.93.87` can you tell me why this is happening?

**Comment by DatMayo** [comment]
Addition:
When I'm using the FQDN `mysql2f67.netcup.net` its translated to `134.209.203.95` which is even more strange

**Comment by martinlevesque** [comment]
@DatMayo Good question, could you request support from the administration with the site name you're using? Difficult to know without the context.

**Comment by DatMayo** [comment]
Ok, sent a ticket :)
