### ISSUE TITLE
Get ip from request header

### ISSUE THREAD

**Issue by loojax** [openode-io/openode-api#439]
Hello last week you resolved that problem , but this last days , i cant get real ip of client .

old config is set now , please fix it on kuber...

**Comment by martinlevesque** [comment]
Strange. Will look at it as soon as possible.

**Comment by martinlevesque** [comment]
It's now again working in USA location

Will also be applied in one week in EU location as we also deployed the following improvement https://github.com/openode-io/openode-api/issues/445
